
print("YO WASSUP")

print("MY NAME IS JOE")
print("I AM A PROGRAMMER")
print("I LOVE PYTHON")
print("I AM A PROGRAMMER")
print("I AM A PROGRAMMER")
print("I AM A PROGRAMMER")
print("MY FAVORITE COLOR IS BLUE")
print("I LOVE CODING")
print("I AM A PROGRAMMER")
